# Generated by Django 3.0.5 on 2020-04-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
